name: Build .NET Core App

on: [push]

jobs:
  build-the-thing:
    strategy:
      matrix:
        dotnet: [ '6.0.x' ]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ubuntu-latest
        
    name: Dotnet ${{ matrix.dotnet }} Sample
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: dotnet build --configuration Release

          
